WebAppBucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:custom.WebAppBucket.name}
    AccessControl: PublicRead
    WebsiteConfiguration:
      IndexDocument: index.html
      ErrorDocument: index.html

WebAppBucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref WebAppBucket
    PolicyDocument:
      Statement:
        - Sid: PublicReadGetObject
          Effect: Allow
          Principal: "*"
          Action:
          - s3:GetObject
          Resource: arn:aws:s3:::${self:custom.WebAppBucket.name}/*
