WebAppCloudFrontDistribution:
  Type: AWS::CloudFront::Distribution
  Properties:
    DistributionConfig:
      Origins:
        - DomainName: ${self:custom.WebAppBucket.endpoint}
          ## An identifier for the origin which must be unique within the distribution
          Id: ${self:custom.WebAppBucket.endpoint}
          CustomOriginConfig:
            HTTPPort: 80
            HTTPSPort: 443
            OriginProtocolPolicy: https-only
          ## In case you want to restrict the bucket access use S3OriginConfig and remove CustomOriginConfig
          # S3OriginConfig:
          #   OriginAccessIdentity: origin-access-identity/cloudfront/E127EXAMPLE51Z
      Enabled: true
      Aliases:
        - ${self:provider.stage}.app.sls-course.jbrunton-aws.com
      ## Uncomment the following section in case you are using a custom domain
      # Aliases:
      # - mysite.example.com
      DefaultRootObject: index.html
      ## Since the Single Page App is taking care of the routing we need to make sure ever path is served with index.html
      ## The only exception are files that actually exist e.h. app.js, reset.css
      CustomErrorResponses:
        - ErrorCode: 404
          ResponseCode: 200
          ResponsePagePath: /index.html
      DefaultCacheBehavior:
        AllowedMethods:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
        ## The origin id defined above
        TargetOriginId: ${self:custom.WebAppBucket.endpoint}
        ## Defining if and how the QueryString and Cookies are forwarded to the origin which in this case is S3
        ForwardedValues:
          QueryString: 'false'
          Cookies:
            Forward: none
        ## The protocol that users can use to access the files in the origin. To allow HTTP use `allow-all`
        ViewerProtocolPolicy: redirect-to-https
      ## The certificate to use when viewers use HTTPS to request objects.
      ViewerCertificate:
        AcmCertificateArn: arn:aws:acm:us-east-1:030461922427:certificate/934c6be4-c062-4506-8017-2e6ad5bfc70e
        SslSupportMethod: 'sni-only'
        MinimumProtocolVersion: 'TLSv1.2_2019'
      ## Uncomment the following section in case you want to enable logging for CloudFront requests
      # Logging:
      #   IncludeCookies: 'false'
      #   Bucket: mylogs.s3.amazonaws.com
      #   Prefix: myprefix