name: Remove

on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Stage'     
        required: true

jobs:

  deploy:
  
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Serverless
        run: npm install -g serverless

      - name: Remove Web-App-Service
        run: |
          npm ci
          sls remove --stage ${{ github.event.inputs.stage }}
        working-directory: web-app-service

      - name: Remove Auction-Service
        run: |
          npm ci
          sls remove --stage ${{ github.event.inputs.stage }}
        working-directory: auction-service

      - name: Remove Notification-Service
        run: |
          npm ci
          sls remove --stage ${{ github.event.inputs.stage }}
        working-directory: notification-service

      - name: Remove Auth-Service
        run: |
          npm ci
          sls remove --stage ${{ github.event.inputs.stage }}
        working-directory: auth-service
